import { ChickFont } from "@/constants/chick-fonts";
import { ChickIntelPalette } from "@/constants/chickintel-palette";

export const ReportsCardTheme = {
    borderRadius: 15,
    borderColor: "rgba(255, 255, 255, 0.6)",
    surfaceBorderColor: ChickIntelPalette.lightGreen,
    surfacePadding: 12,
    titleFontFamily: ChickFont.display,
    titleFontSize: 18,
    titleLineHeight: 24,
    titleFontWeight: "600" as const,
    titleColor: ChickIntelPalette.gray1,
    labelFontFamily: ChickFont.sans,
    labelFontSize: 13,
    labelFontWeight: "600" as const,
    labelColor: ChickIntelPalette.gray1,
    valueFontFamily: ChickFont.sans,
    valueFontSize: 15,
    valueFontWeight: "700" as const,
    valueColor: ChickIntelPalette.gray1,
    chipFontFamily: ChickFont.sans,
    chipFontSize: 12,
    chipFontWeight: "600" as const,
    chipTextColor: ChickIntelPalette.gray1,
    chipSelectedTextColor: "#FFFFFF",
    chipRadius: 20,
    donutSize: 140,
    donutStrokeWidth: 28,
    donutRadius: 6,
    centerValueFontFamily: ChickFont.sans,
    centerValueFontSize: 15,
    centerValueFontWeight: "700" as const,
    centerValueColor: ChickIntelPalette.gray1,
    centerLabelFontFamily: ChickFont.sans,
    centerLabelFontSize: 11,
    centerLabelColor: "#666",
    sectionTitleFontFamily: ChickFont.sans,
    sectionTitleFontSize: 11,
    sectionTitleFontWeight: "600" as const,
    sectionTitleColor: ChickIntelPalette.gray1,
    footerTextFontFamily: ChickFont.sans,
    footerTextFontSize: 11,
    footerTextLineHeight: 16,
    footerTextColor: "#666",
} as const;

export const ReportsPageTheme = {
    screenBackground: ChickIntelPalette.light1,
    contentPaddingHorizontal: 16,
    contentGap: 12,
    headerPaddingHorizontal: 20,
    headerTopMargin: 10,
    headerBottomMargin: 8,
    screenTitle: {
        fontFamily: ChickFont.display,
        fontSize: 20,
        lineHeight: 30,
        fontWeight: "800" as const,
        letterSpacing: -0.55,
        color: ChickIntelPalette.gray1,
    },
    printButtonSize: 44,
    printButtonRadius: 22,
    printButtonBackground: "rgba(255,255,255,0.4)",
    printButtonBorderColor: "rgba(255,255,255,0.6)",
    cardOuterRadius: 15,
    cardInnerRadius: 15,
    cardInnerPadding: 12,
    modalRadius: 15,
    modalPadding: 20,
    modalHeaderSpacing: 20,
    optionSelectedBackground: "rgba(49, 118, 103, 0.05)",
    dropdownLabelColor: ChickIntelPalette.gray1,
    dropdownValueColor: ChickIntelPalette.gray1,
    dropdownRowHeight: 40,
    dropdownRowPaddingVertical: 8,
    dropdownRowRadius: 8,
    chartTopMargin: 18,
    chartHeight: 172,
    chartContainerSize: 140,
    analyticsTextColor: ChickIntelPalette.gray1,
    footerTopMargin: 18,
} as const;
